# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9b112707298aae01904817b8acf90a836fac1afd331fc907783a333d4bde61b60f11d531a9ee644036917d7c34aaf2a87a9cc691ba8372ba6e73984279e5f7a

test:
  secret_key_base: 88d97e374f7508232c45f1b35d3e7737d0efbcb801ddfa25bef0a16c06131e2324623d4865e82fd6793af3d5b838abc64edce4cd6b47f527eb3d8650be108937

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
